---
http:
  port: 7000
  ip: 127.0.0.1
logs:
  prefix: service-mfa
  console:
    active: true
    level: info
    colorize: true
  file:
    active: false
  airbrake:
    active: true
    projectId: 329486
    key: '6e58a3a296306419137622d180704f5f'
core:
  url: https://co2.pryv.li
sms:
  endpoints:
    challenge: https://api.smsapi.com/mfa/codes
    verify: https://api.smsapi.com/mfa/codes/verifications
  auth: 'Bearer: TUewFvPRTcPI8m8w3t2Ivu70MXN3DrkuOXA2eAbB'
sessions:
  ttlSeconds: 0.2