---
http:
  port: 7000
  ip: 127.0.0.1
logs:
  prefix: service-mfa
  console:
    active: true
    level: info
    colorize: true
  file:
    active: true
    path: mfa.log
  airbrake:
    active: true
    projectId: 329486
    key: '6e58a3a296306419137622d180704f5f'
core:
  url: https://co2.pryv.li
sms:
  mode: 'challenge-verify'  # allowed: 'challenge-verify', 'single'
  endpoints:
    challenge: 
      url: 'https://api.smsapi.com/mfa/codes'
      method: 'POST'
      body: '{{ phoneObject }}'
      headers:
        authorization: 'Bearer: TUewFvPRTcPI8m8w3t2Ivu70MXN3DrkuOXA2eAbB'
        'content-type': 'application/json'
    verify: 
      url: 'https://api.smsapi.com/mfa/codes/verifications'
      method: 'POST'
      body: '{{ phoneObject }}'
      headers:
        authorization: 'Bearer: TUewFvPRTcPI8m8w3t2Ivu70MXN3DrkuOXA2eAbB'
        'content-type': 'application/json'
sessions:
  ttlSeconds: 0.2