---
http:
  port: 7000
  ip: 127.0.0.1
logs:
  prefix: service-mfa
  console:
    active: false
    level: info
    colorize: true
  file:
    active: false
core:
  url: https://co2.pryv.li
sms:
  mode: 'challenge-verify'  # allowed: 'challenge-verify', 'single'
  endpoints:
    challenge: https://api.smsapi.com/mfa/codes
    verify: https://api.smsapi.com/mfa/codes/verifications
    # single: 
    #   url: https://api.smsmode.com/http/1.6/sendSMS.do
    #   method: 'POST'
  auth: 'Bearer: TUewFvPRTcPI8m8w3t2Ivu70MXN3DrkuOXA2eAbB'
  #token: '{{ code }}'
  #variables:
  #  authorization: 'MpBJUQtZPkbWwZ76avvobN1wFdv4K7ls'
sessions:
  ttlSeconds: 0.2