---
http:
  port: 7000
  ip: 127.0.0.1
logs:
  prefix: mfa
  console:
    active: false
    level: info
    colorize: true
  file:
    active: false
core:
  url: https://co2.pryv.li
sms:
  mode: 'challenge-verify'  # allowed: 'challenge-verify', 'single'
  endpoints:
    challenge:
      url: 'https://api.smsapi.com/mfa/codes'
      method: 'POST'
      body: '{"phone_number":"{{ phone_number }}"}'
      headers:
        authorization: 'Bearer TUewFvPRTcPI8m8w3t2Ivu70MXN3DrkuOXA2eAbB'
        'content-type': 'application/json'
    verify:
      url: 'https://api.smsapi.com/mfa/codes/verifications'
      method: 'POST'
      body: '{"phone_number":"{{ phone_number }}","code":"{{ code }}"}'
      headers:
        authorization: 'Bearer TUewFvPRTcPI8m8w3t2Ivu70MXN3DrkuOXA2eAbB'
        'content-type': 'application/json'
    single:
      url: https://api.smsmode.com/http/1.6/sendSMS.do?accessToken=MpBJUQtZPkbWwZ76avvobN1wFdv4K7ls&message={{ code }}&emetteur=Pryv%20Lab&numero={{ phone_number }}
      method: 'GET'
sessions:
  ttlSeconds: 0.2
