name: Pryv.io MFA tests

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  run-tests:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.13]

    steps:
    - name: Download master branch
      uses: actions/checkout@v2
    
    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: yarn install
      
    - name: yarn release
      run: yarn release
        
    - name: yarn test
      run: yarn test