name: Pryv.io MFA release

on: 
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: yarn install
      
    - name: yarn release
      run: yarn release
        
    - name: yarn test
      run: yarn test

    - name: Build and deploy
      run: ./build/build