name: Pryv.io MFA release

on: 
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Build and deploy
      run: ./build/build_workflow