name: Pryv.io MFA release

on: 
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest
    
    steps:
    - name: Download master branch
      uses: actions/checkout@v2

    - name: Install Node.js with version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: yarn install
      run: yarn install
      
    - name: yarn release
      run: yarn release
        
    - name: yarn test
      run: yarn test

    - name: Login to the docker containers registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
        username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
        password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

    - name: Download base image and change the tag
      run: |
        docker pull ${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/base:1.3.40
        docker tag "${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/base:1.3.40" "pryvio/base:1.3.40"

    - name: Build and deploy
      run: ./build/build